---
- name: Pull Docker image of Calculator
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: pull docker image
      shell: docker pull bean6792/calculator:latest
