---
- name: Pull Docker image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: install Docker python module
      pip:
        name: docker
        state: present
    - name: Pull image
      docker_image:
        name: bean6792/calculator:latest
        source: pull
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name Unscientific bean6792/calculator
